<?php

namespace BondarDe\Emoji\PeopleAndBody;

class Hands
{
    const CLAPPING_HANDS = '👏';
    const CLAPPING_HANDS_LIGHT_SKIN_TONE = '👏🏻';
    const CLAPPING_HANDS_MEDIUM_LIGHT_SKIN_TONE = '👏🏼';
    const CLAPPING_HANDS_MEDIUM_SKIN_TONE = '👏🏽';
    const CLAPPING_HANDS_MEDIUM_DARK_SKIN_TONE = '👏🏾';
    const CLAPPING_HANDS_DARK_SKIN_TONE = '👏🏿';
    const RAISING_HANDS = '🙌';
    const RAISING_HANDS_LIGHT_SKIN_TONE = '🙌🏻';
    const RAISING_HANDS_MEDIUM_LIGHT_SKIN_TONE = '🙌🏼';
    const RAISING_HANDS_MEDIUM_SKIN_TONE = '🙌🏽';
    const RAISING_HANDS_MEDIUM_DARK_SKIN_TONE = '🙌🏾';
    const RAISING_HANDS_DARK_SKIN_TONE = '🙌🏿';
    const HEART_HANDS = '🫶';
    const HEART_HANDS_LIGHT_SKIN_TONE = '🫶🏻';
    const HEART_HANDS_MEDIUM_LIGHT_SKIN_TONE = '🫶🏼';
    const HEART_HANDS_MEDIUM_SKIN_TONE = '🫶🏽';
    const HEART_HANDS_MEDIUM_DARK_SKIN_TONE = '🫶🏾';
    const HEART_HANDS_DARK_SKIN_TONE = '🫶🏿';
    const OPEN_HANDS = '👐';
    const OPEN_HANDS_LIGHT_SKIN_TONE = '👐🏻';
    const OPEN_HANDS_MEDIUM_LIGHT_SKIN_TONE = '👐🏼';
    const OPEN_HANDS_MEDIUM_SKIN_TONE = '👐🏽';
    const OPEN_HANDS_MEDIUM_DARK_SKIN_TONE = '👐🏾';
    const OPEN_HANDS_DARK_SKIN_TONE = '👐🏿';
    const PALMS_UP_TOGETHER = '🤲';
    const PALMS_UP_TOGETHER_LIGHT_SKIN_TONE = '🤲🏻';
    const PALMS_UP_TOGETHER_MEDIUM_LIGHT_SKIN_TONE = '🤲🏼';
    const PALMS_UP_TOGETHER_MEDIUM_SKIN_TONE = '🤲🏽';
    const PALMS_UP_TOGETHER_MEDIUM_DARK_SKIN_TONE = '🤲🏾';
    const PALMS_UP_TOGETHER_DARK_SKIN_TONE = '🤲🏿';
    const HANDSHAKE = '🤝';
    const HANDSHAKE_LIGHT_SKIN_TONE = '🤝🏻';
    const HANDSHAKE_MEDIUM_LIGHT_SKIN_TONE = '🤝🏼';
    const HANDSHAKE_MEDIUM_SKIN_TONE = '🤝🏽';
    const HANDSHAKE_MEDIUM_DARK_SKIN_TONE = '🤝🏾';
    const HANDSHAKE_DARK_SKIN_TONE = '🤝🏿';
    const HANDSHAKE_LIGHT_SKIN_TONE_MEDIUM_LIGHT_SKIN_TONE = '🫱🏻‍🫲🏼';
    const HANDSHAKE_LIGHT_SKIN_TONE_MEDIUM_SKIN_TONE = '🫱🏻‍🫲🏽';
    const HANDSHAKE_LIGHT_SKIN_TONE_MEDIUM_DARK_SKIN_TONE = '🫱🏻‍🫲🏾';
    const HANDSHAKE_LIGHT_SKIN_TONE_DARK_SKIN_TONE = '🫱🏻‍🫲🏿';
    const HANDSHAKE_MEDIUM_LIGHT_SKIN_TONE_LIGHT_SKIN_TONE = '🫱🏼‍🫲🏻';
    const HANDSHAKE_MEDIUM_LIGHT_SKIN_TONE_MEDIUM_SKIN_TONE = '🫱🏼‍🫲🏽';
    const HANDSHAKE_MEDIUM_LIGHT_SKIN_TONE_MEDIUM_DARK_SKIN_TONE = '🫱🏼‍🫲🏾';
    const HANDSHAKE_MEDIUM_LIGHT_SKIN_TONE_DARK_SKIN_TONE = '🫱🏼‍🫲🏿';
    const HANDSHAKE_MEDIUM_SKIN_TONE_LIGHT_SKIN_TONE = '🫱🏽‍🫲🏻';
    const HANDSHAKE_MEDIUM_SKIN_TONE_MEDIUM_LIGHT_SKIN_TONE = '🫱🏽‍🫲🏼';
    const HANDSHAKE_MEDIUM_SKIN_TONE_MEDIUM_DARK_SKIN_TONE = '🫱🏽‍🫲🏾';
    const HANDSHAKE_MEDIUM_SKIN_TONE_DARK_SKIN_TONE = '🫱🏽‍🫲🏿';
    const HANDSHAKE_MEDIUM_DARK_SKIN_TONE_LIGHT_SKIN_TONE = '🫱🏾‍🫲🏻';
    const HANDSHAKE_MEDIUM_DARK_SKIN_TONE_MEDIUM_LIGHT_SKIN_TONE = '🫱🏾‍🫲🏼';
    const HANDSHAKE_MEDIUM_DARK_SKIN_TONE_MEDIUM_SKIN_TONE = '🫱🏾‍🫲🏽';
    const HANDSHAKE_MEDIUM_DARK_SKIN_TONE_DARK_SKIN_TONE = '🫱🏾‍🫲🏿';
    const HANDSHAKE_DARK_SKIN_TONE_LIGHT_SKIN_TONE = '🫱🏿‍🫲🏻';
    const HANDSHAKE_DARK_SKIN_TONE_MEDIUM_LIGHT_SKIN_TONE = '🫱🏿‍🫲🏼';
    const HANDSHAKE_DARK_SKIN_TONE_MEDIUM_SKIN_TONE = '🫱🏿‍🫲🏽';
    const HANDSHAKE_DARK_SKIN_TONE_MEDIUM_DARK_SKIN_TONE = '🫱🏿‍🫲🏾';
    const FOLDED_HANDS = '🙏';
    const FOLDED_HANDS_LIGHT_SKIN_TONE = '🙏🏻';
    const FOLDED_HANDS_MEDIUM_LIGHT_SKIN_TONE = '🙏🏼';
    const FOLDED_HANDS_MEDIUM_SKIN_TONE = '🙏🏽';
    const FOLDED_HANDS_MEDIUM_DARK_SKIN_TONE = '🙏🏾';
    const FOLDED_HANDS_DARK_SKIN_TONE = '🙏🏿';
}
