<?php

namespace BondarDe\Emoji\PeopleAndBody;

use BondarDe\Emoji\HasStaticGetters;

class HandSingleFinger
{
    use HasStaticGetters;

    const BACKHAND_INDEX_POINTING_LEFT = '👈';
    const BACKHAND_INDEX_POINTING_LEFT_LIGHT_SKIN_TONE = '👈🏻';
    const BACKHAND_INDEX_POINTING_LEFT_MEDIUM_LIGHT_SKIN_TONE = '👈🏼';
    const BACKHAND_INDEX_POINTING_LEFT_MEDIUM_SKIN_TONE = '👈🏽';
    const BACKHAND_INDEX_POINTING_LEFT_MEDIUM_DARK_SKIN_TONE = '👈🏾';
    const BACKHAND_INDEX_POINTING_LEFT_DARK_SKIN_TONE = '👈🏿';
    const BACKHAND_INDEX_POINTING_RIGHT = '👉';
    const BACKHAND_INDEX_POINTING_RIGHT_LIGHT_SKIN_TONE = '👉🏻';
    const BACKHAND_INDEX_POINTING_RIGHT_MEDIUM_LIGHT_SKIN_TONE = '👉🏼';
    const BACKHAND_INDEX_POINTING_RIGHT_MEDIUM_SKIN_TONE = '👉🏽';
    const BACKHAND_INDEX_POINTING_RIGHT_MEDIUM_DARK_SKIN_TONE = '👉🏾';
    const BACKHAND_INDEX_POINTING_RIGHT_DARK_SKIN_TONE = '👉🏿';
    const BACKHAND_INDEX_POINTING_UP = '👆';
    const BACKHAND_INDEX_POINTING_UP_LIGHT_SKIN_TONE = '👆🏻';
    const BACKHAND_INDEX_POINTING_UP_MEDIUM_LIGHT_SKIN_TONE = '👆🏼';
    const BACKHAND_INDEX_POINTING_UP_MEDIUM_SKIN_TONE = '👆🏽';
    const BACKHAND_INDEX_POINTING_UP_MEDIUM_DARK_SKIN_TONE = '👆🏾';
    const BACKHAND_INDEX_POINTING_UP_DARK_SKIN_TONE = '👆🏿';
    const MIDDLE_FINGER = '🖕';
    const MIDDLE_FINGER_LIGHT_SKIN_TONE = '🖕🏻';
    const MIDDLE_FINGER_MEDIUM_LIGHT_SKIN_TONE = '🖕🏼';
    const MIDDLE_FINGER_MEDIUM_SKIN_TONE = '🖕🏽';
    const MIDDLE_FINGER_MEDIUM_DARK_SKIN_TONE = '🖕🏾';
    const MIDDLE_FINGER_DARK_SKIN_TONE = '🖕🏿';
    const BACKHAND_INDEX_POINTING_DOWN = '👇';
    const BACKHAND_INDEX_POINTING_DOWN_LIGHT_SKIN_TONE = '👇🏻';
    const BACKHAND_INDEX_POINTING_DOWN_MEDIUM_LIGHT_SKIN_TONE = '👇🏼';
    const BACKHAND_INDEX_POINTING_DOWN_MEDIUM_SKIN_TONE = '👇🏽';
    const BACKHAND_INDEX_POINTING_DOWN_MEDIUM_DARK_SKIN_TONE = '👇🏾';
    const BACKHAND_INDEX_POINTING_DOWN_DARK_SKIN_TONE = '👇🏿';
    const INDEX_POINTING_UP = '☝️';
    const INDEX_POINTING_UP_LIGHT_SKIN_TONE = '☝🏻';
    const INDEX_POINTING_UP_MEDIUM_LIGHT_SKIN_TONE = '☝🏼';
    const INDEX_POINTING_UP_MEDIUM_SKIN_TONE = '☝🏽';
    const INDEX_POINTING_UP_MEDIUM_DARK_SKIN_TONE = '☝🏾';
    const INDEX_POINTING_UP_DARK_SKIN_TONE = '☝🏿';
    const INDEX_POINTING_AT_THE_VIEWER = '🫵';
    const INDEX_POINTING_AT_THE_VIEWER_LIGHT_SKIN_TONE = '🫵🏻';
    const INDEX_POINTING_AT_THE_VIEWER_MEDIUM_LIGHT_SKIN_TONE = '🫵🏼';
    const INDEX_POINTING_AT_THE_VIEWER_MEDIUM_SKIN_TONE = '🫵🏽';
    const INDEX_POINTING_AT_THE_VIEWER_MEDIUM_DARK_SKIN_TONE = '🫵🏾';
    const INDEX_POINTING_AT_THE_VIEWER_DARK_SKIN_TONE = '🫵🏿';
}
