<?php

namespace BondarDe\Emoji\PeopleAndBody;

use BondarDe\Emoji\HasStaticGetters;

class PersonResting
{
    use HasStaticGetters;

    const PERSON_IN_LOTUS_POSITION = '🧘';
    const PERSON_IN_LOTUS_POSITION_LIGHT_SKIN_TONE = '🧘🏻';
    const PERSON_IN_LOTUS_POSITION_MEDIUM_LIGHT_SKIN_TONE = '🧘🏼';
    const PERSON_IN_LOTUS_POSITION_MEDIUM_SKIN_TONE = '🧘🏽';
    const PERSON_IN_LOTUS_POSITION_MEDIUM_DARK_SKIN_TONE = '🧘🏾';
    const PERSON_IN_LOTUS_POSITION_DARK_SKIN_TONE = '🧘🏿';
    const MAN_IN_LOTUS_POSITION = '🧘‍♂️';
    const MAN_IN_LOTUS_POSITION_LIGHT_SKIN_TONE = '🧘🏻‍♂️';
    const MAN_IN_LOTUS_POSITION_MEDIUM_LIGHT_SKIN_TONE = '🧘🏼‍♂️';
    const MAN_IN_LOTUS_POSITION_MEDIUM_SKIN_TONE = '🧘🏽‍♂️';
    const MAN_IN_LOTUS_POSITION_MEDIUM_DARK_SKIN_TONE = '🧘🏾‍♂️';
    const MAN_IN_LOTUS_POSITION_DARK_SKIN_TONE = '🧘🏿‍♂️';
    const WOMAN_IN_LOTUS_POSITION = '🧘‍♀️';
    const WOMAN_IN_LOTUS_POSITION_LIGHT_SKIN_TONE = '🧘🏻‍♀️';
    const WOMAN_IN_LOTUS_POSITION_MEDIUM_LIGHT_SKIN_TONE = '🧘🏼‍♀️';
    const WOMAN_IN_LOTUS_POSITION_MEDIUM_SKIN_TONE = '🧘🏽‍♀️';
    const WOMAN_IN_LOTUS_POSITION_MEDIUM_DARK_SKIN_TONE = '🧘🏾‍♀️';
    const WOMAN_IN_LOTUS_POSITION_DARK_SKIN_TONE = '🧘🏿‍♀️';
    const PERSON_TAKING_BATH = '🛀';
    const PERSON_TAKING_BATH_LIGHT_SKIN_TONE = '🛀🏻';
    const PERSON_TAKING_BATH_MEDIUM_LIGHT_SKIN_TONE = '🛀🏼';
    const PERSON_TAKING_BATH_MEDIUM_SKIN_TONE = '🛀🏽';
    const PERSON_TAKING_BATH_MEDIUM_DARK_SKIN_TONE = '🛀🏾';
    const PERSON_TAKING_BATH_DARK_SKIN_TONE = '🛀🏿';
    const PERSON_IN_BED = '🛌';
    const PERSON_IN_BED_LIGHT_SKIN_TONE = '🛌🏻';
    const PERSON_IN_BED_MEDIUM_LIGHT_SKIN_TONE = '🛌🏼';
    const PERSON_IN_BED_MEDIUM_SKIN_TONE = '🛌🏽';
    const PERSON_IN_BED_MEDIUM_DARK_SKIN_TONE = '🛌🏾';
    const PERSON_IN_BED_DARK_SKIN_TONE = '🛌🏿';
}
